### ISSUE TITLE
unable to configure host when building swagger UI

### ISSUE THREAD

**Issue by radai-rosenblatt** [int128/gradle-swagger-generator-plugin#41]
im using swagger ui 2.2.10
generated code tried to do this:
```
// Overwrite options
$.each(
{
  "url" : "",
  "validatorUrl" : null,
  "host" : "localhost"
},
function (key, value) { window.swaggerUi.setOption(key, value) }
);
```
but looks like the correct API would be by using `window.swaggerUi.api` (see https://github.com/swagger-api/swagger-js/issues/532).

specifically in my case the following expression worked: 
```
window.swaggerUi.api.setHost("overriddenHostName")
```

**Comment by albertotn** [comment]
I'm also on this!

**My scenario**: I'm writing a swagger for different enviroments (local, test, production) so with different url.
**Problem**: because I'm not able to find a proper way to specify which enviroment generator plugin should generate for, I'm using gradle profiles to search for file with host reference and update them, for example:

on build.gradle:

```
// apply enviroment properties, used on command line with gradle -PbuildProfile=test clean build
if (!hasProperty('buildProfile')) ext.buildProfile = 'default'
apply from: "profile-${buildProfile}.gradle"
```

my test profile file:

// Test enviroment properties (for deploy on AWS test machine)


```
war {
	// apply on swagger-ui to change localhost:8080 to host:port  
	rootSpec.eachFile {
    	if (it.name == 'swagger-spec.js') {
        	filter { line ->
            	line.replace('localhost:8080', "testhost.com")
        	}
    	}
	}
}
```

**Request**: there is a proper way to override host, port and basepath like @radai-rosenblatt requested, directly in this plugin ?

**Comment by int128** [comment]
You can override index.html as https://github.com/int128/gradle-swagger-generator-plugin#configure-swagger-ui since [version 2.10.0](https://github.com/int128/gradle-swagger-generator-plugin/releases/tag/2.10.0).
